import type { AnalyticsPageData } from "./types";

export const analyticsPageData: AnalyticsPageData = {
  periodOptions: [
    { id: "7d", label: "7 дней" },
    { id: "30d", label: "30 дней" },
    { id: "90d", label: "90 дней" },
  ],
  greenhouseOptions: [
    { id: "all", label: "Все теплицы" },
    { id: "a12", label: "A-12" },
    { id: "b04", label: "B-04" },
    { id: "c07", label: "C-07" },
  ],
  cropOptions: [
    { id: "all", label: "Все культуры" },
    { id: "tomato", label: "Томаты" },
    { id: "cucumber", label: "Огурцы" },
    { id: "basil", label: "Базилик" },
  ],
  kpis: [
    {
      id: "healthy",
      label: "Здоровые растения",
      value: "82.4%",
      detail: "10 284 растений находятся в стабильном состоянии по активным секторам.",
      trend: "+2.3% к прошлому периоду",
      tone: "good",
    },
    {
      id: "alerts",
      label: "Сигналы заболеваний",
      value: "37",
      detail: "11 сигналов были переданы на проверку агроному.",
      trend: "-12% к прошлому периоду",
      tone: "warning",
    },
    {
      id: "cameras",
      label: "Активные камеры",
      value: "19 / 20",
      detail: "Один поток в B-04 находится на диагностике.",
      trend: "95% доступности сети",
      tone: "neutral",
    },
    {
      id: "accuracy",
      label: "Точность ML",
      value: "98.7%",
      detail: "Уверенность модели в диагностике остается стабильной.",
      trend: "+0.6% к прошлому периоду",
      tone: "good",
    },
    {
      id: "latency",
      label: "Среднее время отклика",
      value: "1.8 сек",
      detail: "Среднее время от снимка до отображения сигнала на frontend.",
      trend: "-0.4 сек к прошлому периоду",
      tone: "good",
    },
  ],
  trend: [
    { day: "Пн", alerts: 18, resolved: 14 },
    { day: "Вт", alerts: 24, resolved: 18 },
    { day: "Ср", alerts: 29, resolved: 22 },
    { day: "Чт", alerts: 21, resolved: 20 },
    { day: "Пт", alerts: 33, resolved: 26 },
    { day: "Сб", alerts: 27, resolved: 24 },
    { day: "Вс", alerts: 19, resolved: 17 },
  ],
  heatmap: [
    {
      id: "row-a",
      title: "A-12",
      cells: [
        { id: "a1", label: "A1", state: "good", note: "Стабильный рост" },
        { id: "a2", label: "A2", state: "good", note: "Риск не обнаружен" },
        { id: "a3", label: "A3", state: "warning", note: "Скачок влажности" },
        { id: "a4", label: "A4", state: "good", note: "Сбалансированный климат" },
      ],
    },
    {
      id: "row-b",
      title: "B-04",
      cells: [
        { id: "b1", label: "B1", state: "warning", note: "Ранний грибковый риск" },
        { id: "b2", label: "B2", state: "critical", note: "Слепая зона камеры" },
        { id: "b3", label: "B3", state: "warning", note: "Изменение цвета листа" },
        { id: "b4", label: "B4", state: "good", note: "Нормальное восстановление" },
      ],
    },
    {
      id: "row-c",
      title: "C-07",
      cells: [
        { id: "c1", label: "C1", state: "critical", note: "Бактериальный паттерн" },
        { id: "c2", label: "C2", state: "critical", note: "Риск распространения" },
        { id: "c3", label: "C3", state: "warning", note: "Проверить соседний блок" },
        { id: "c4", label: "C4", state: "good", note: "Чистый сигнал" },
      ],
    },
  ],
  diseases: [
    {
      id: "fungal",
      name: "Риск грибкового поражения",
      spread: "32%",
      risk: "Высокий",
      shareClass: "share72",
      tone: "critical",
    },
    {
      id: "bacterial",
      name: "Бактериальная пятнистость",
      spread: "24%",
      risk: "Средний",
      shareClass: "share54",
      tone: "warning",
    },
    {
      id: "nutrient",
      name: "Стресс из-за питания",
      spread: "17%",
      risk: "Средний",
      shareClass: "share38",
      tone: "warning",
    },
    {
      id: "watering",
      name: "Дисбаланс полива",
      spread: "11%",
      risk: "Низкий",
      shareClass: "share27",
      tone: "good",
    },
    {
      id: "other",
      name: "Другие аномалии",
      spread: "7%",
      risk: "Низкий",
      shareClass: "share18",
      tone: "good",
    },
  ],
  insights: [
    {
      id: "insight-1",
      title: "B-04 требует коррекции микроклимата уже сегодня",
      description:
        "Система связывает повышенную влажность и медленное высыхание листа с ростом грибкового риска на среднем ярусе теплицы B-04.",
      tone: "warning",
    },
    {
      id: "insight-2",
      title: "C-07 нужно передать на ручную проверку агроному",
      description:
        "Повторяющийся визуальный паттерн больше похож на бактериальную пятнистость, чем на временный артефакт камеры. Рекомендуется очная проверка в ближайший обход.",
      tone: "critical",
    },
    {
      id: "insight-3",
      title: "A-12 остается эталонным здоровым сектором",
      description:
        "В этой теплице стабильны температура, влажность и плотность аномалий, поэтому ее удобно использовать как базу для сравнения с более слабыми блоками.",
      tone: "good",
    },
  ],
  comparison: [
    {
      id: "healthy",
      label: "Доля здоровых растений",
      current: "82.4%",
      previous: "80.1%",
      delta: "+2.3%",
      trend: "up",
    },
    {
      id: "alerts",
      label: "Критические сигналы",
      current: "37",
      previous: "42",
      delta: "-5",
      trend: "down",
    },
    {
      id: "latency",
      label: "Средняя задержка",
      current: "1.8 сек",
      previous: "2.2 сек",
      delta: "-0.4 сек",
      trend: "down",
    },
    {
      id: "coverage",
      label: "Покрытие камерами",
      current: "95%",
      previous: "92%",
      delta: "+3%",
      trend: "up",
    },
  ],
  activity: [
    {
      id: "activity-1",
      time: "15:24",
      title: "Блок томатов A-12 отмечен как здоровый",
      description: "ML завершил полный скан без значимых признаков заболевания.",
      tone: "good",
    },
    {
      id: "activity-2",
      time: "15:12",
      title: "Сигнал по влажности в B-04 повышен в приоритете",
      description: "Три камеры подтвердили устойчивое удержание влаги после полива.",
      tone: "warning",
    },
    {
      id: "activity-3",
      time: "14:57",
      title: "В C-07 найден возможный бактериальный паттерн",
      description: "Повторяющийся кластер пятен получил высокий приоритет для ручной проверки.",
      tone: "critical",
    },
    {
      id: "activity-4",
      time: "14:41",
      title: "Сформирован недельный сравнительный отчет",
      description: "Frontend получил свежую аналитическую сводку после backend-обработки.",
      tone: "neutral",
    },
  ],
  mlStatus: {
    title: "Статус ML-системы",
    state: "Работает стабильно",
    stateTone: "good",
    description:
      "Пайплайны инференса работают без перегрузки, очередь обработки низкая, а backend продолжает без перерывов передавать аналитику в dashboard.",
    lastUpdate: "Обновлено 2 минуты назад",
    metrics: [
      { id: "processed", label: "Обработано изображений", value: "128 430" },
      { id: "accuracy", label: "Точность", value: "98.7%" },
      { id: "latency", label: "Задержка", value: "1.8 сек" },
      { id: "uptime", label: "Аптайм", value: "99.94%" },
    ],
  },
};
